use crate::scanner::ScanResults;
use crate::ue::props::{ClassDump, EnumDump, FunctionDump, PropertyDump};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt::Write;

// ═══════════════════════════════════════════════════════════════════
//  Public entry points
// ═══════════════════════════════════════════════════════════════════

/// Generate Rust source code with `#[repr(C)]` structs, parent embedding,
/// const offset tables, bitfield accessors, UFunction address constants,
/// UEnum variant modules, size asserts, and per-package modules.
pub fn generate_rust(
    classes: &[ClassDump],
    enums: &[EnumDump],
    globals: Option<&ScanResults>,
    base: usize,
) -> String {
    let mut out = String::with_capacity(512 * 1024);
    emit_header(&mut out);
    emit_common_types(&mut out);
    if let Some(g) = globals {
        emit_globals(&mut out, g, base);
    }
    emit_enums_module(&mut out, enums);
    emit_package_modules(&mut out, classes);
    out
}

/// Generate pointer-chain constants for reaching the local player pawn from GWorld.
///
/// Emits offsets for the standard UE5 chain:
///   GWorld -> UWorld.OwningGameInstance -> UGameInstance.LocalPlayers[0]
///          -> ULocalPlayer.PlayerController -> APlayerController.AcknowledgedPawn
///
/// A WARNING comment is emitted for any step missing from the dump.
pub fn generate_chain(classes: &[ClassDump], gworld_offset: usize) -> String {
    let mut out = String::with_capacity(1024);

    writeln!(out, "// Auto-generated player-pawn pointer chain by ue5-dumper").unwrap();
    writeln!(out, "// Generated: {}", timestamp()).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub const OFF_GWORLD: usize = {gworld_offset:#X};").unwrap();

    if let Some(off) = find_property_offset(classes, "World", "OwningGameInstance") {
        writeln!(out, "pub const OFF_GAME_INSTANCE: usize = {off:#X};").unwrap();
    } else {
        writeln!(out, "// WARNING: World.OwningGameInstance not found in dump").unwrap();
    }

    if let Some(off) = find_property_offset(classes, "GameInstance", "LocalPlayers") {
        writeln!(out, "pub const OFF_LOCAL_PLAYERS: usize = {off:#X};").unwrap();
    } else {
        writeln!(out, "// WARNING: GameInstance.LocalPlayers not found in dump").unwrap();
    }

    if let Some(off) = find_property_offset(classes, "PlayerController", "Player") {
        writeln!(out, "// Hint: PlayerController.Player = {off:#X}").unwrap();
    }
    if let Some(off) = find_property_offset(classes, "Player", "PlayerController") {
        writeln!(out, "pub const OFF_PLAYER_CONTROLLER: usize = {off:#X}; // UPlayer.PlayerController").unwrap();
    } else {
        writeln!(out, "// WARNING: Player.PlayerController not found in dump").unwrap();
    }

    if let Some(off) = find_property_offset(classes, "PlayerController", "AcknowledgedPawn") {
        writeln!(out, "pub const OFF_ACKNOWLEDGED_PAWN: usize = {off:#X};").unwrap();
    } else {
        writeln!(out, "// WARNING: PlayerController.AcknowledgedPawn not found in dump").unwrap();
    }

    out
}

// ═══════════════════════════════════════════════════════════════════
//  Header / common types / globals
// ═══════════════════════════════════════════════════════════════════

fn emit_header(out: &mut String) {
    writeln!(out, "// Auto-generated by ue5-dumper").unwrap();
    writeln!(out, "// Generated: {}", timestamp()).unwrap();
    writeln!(
        out,
        "#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals, ambiguous_glob_reexports)]"
    )
    .unwrap();
    writeln!(out).unwrap();
}

fn emit_common_types(out: &mut String) {
    writeln!(out, "use core::marker::PhantomData;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "// ── Common UE types ──────────────────────────────────────────────").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "#[repr(C)]").unwrap();
    writeln!(out, "#[derive(Copy, Clone, Debug)]").unwrap();
    writeln!(out, "pub struct FName {{").unwrap();
    writeln!(out, "    pub comparison_index: u32,").unwrap();
    writeln!(out, "    pub number: u32,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "#[repr(C)]").unwrap();
    writeln!(out, "#[derive(Copy, Clone, Debug)]").unwrap();
    writeln!(out, "pub struct FString {{").unwrap();
    writeln!(out, "    pub data: *const u16,").unwrap();
    writeln!(out, "    pub len: i32,").unwrap();
    writeln!(out, "    pub cap: i32,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // TArray<T>: manual Copy/Clone/Debug impls so users don't need T: Copy/Debug.
    writeln!(out, "#[repr(C)]").unwrap();
    writeln!(out, "pub struct TArray<T> {{").unwrap();
    writeln!(out, "    pub data: *const T,").unwrap();
    writeln!(out, "    pub len: i32,").unwrap();
    writeln!(out, "    pub cap: i32,").unwrap();
    writeln!(out, "    _marker: PhantomData<T>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "impl<T> Copy for TArray<T> {{}}").unwrap();
    writeln!(out, "impl<T> Clone for TArray<T> {{ fn clone(&self) -> Self {{ *self }} }}").unwrap();
    writeln!(out, "impl<T> core::fmt::Debug for TArray<T> {{").unwrap();
    writeln!(out, "    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{").unwrap();
    writeln!(out, "        f.debug_struct(\"TArray\").field(\"data\", &self.data).field(\"len\", &self.len).field(\"cap\", &self.cap).finish()").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_globals(out: &mut String, g: &ScanResults, base: usize) {
    let (gnames_off, gobjects_off, gworld_off) = g.offsets(base);
    writeln!(out, "// ── Globals (relative to image base) ─────────────────────────────").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub const GWORLD: usize = {gworld_off:#X};").unwrap();
    writeln!(out, "pub const GNAMES: usize = {gnames_off:#X};").unwrap();
    writeln!(out, "pub const GOBJECTS: usize = {gobjects_off:#X};").unwrap();
    writeln!(out).unwrap();
}

// ═══════════════════════════════════════════════════════════════════
//  Enums
// ═══════════════════════════════════════════════════════════════════

fn emit_enums_module(out: &mut String, enums: &[EnumDump]) {
    if enums.is_empty() {
        return;
    }

    writeln!(out, "// ── UEnum dumps ──────────────────────────────────────────────────").unwrap();
    writeln!(out, "pub mod enums {{").unwrap();
    writeln!(out, "    //! Each UEnum is a nested module of `pub const NAME: i64 = ...;`.").unwrap();
    writeln!(out, "    //! i64 is used because UEnum stores raw values as int64 internally;").unwrap();
    writeln!(out, "    //! cast to the backing integer width the property expects.").unwrap();
    writeln!(out).unwrap();
    for e in enums {
        let mod_name = sanitize_ident(&e.name);
        writeln!(out, "    /// {} (full: {})", e.name, e.full_name).unwrap();
        writeln!(out, "    pub mod {mod_name} {{").unwrap();
        for v in &e.variants {
            // Strip enum-name prefix: "EFoo::Bar" -> "Bar"
            let short = v.name.rsplit("::").next().unwrap_or(&v.name);
            let ident = sanitize_ident(short);
            writeln!(out, "        pub const {ident}: i64 = {};", v.value).unwrap();
        }
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

// ═══════════════════════════════════════════════════════════════════
//  Package grouping + module emission
// ═══════════════════════════════════════════════════════════════════

fn emit_package_modules(out: &mut String, classes: &[ClassDump]) {
    // Topologically sort so parents come before children.
    let class_by_name: HashMap<&str, &ClassDump> =
        classes.iter().map(|c| (c.name.as_str(), c)).collect();
    let ordered = topo_sort(classes, &class_by_name);

    let known_structs: HashSet<&str> = classes.iter().map(|c| c.name.as_str()).collect();

    // Derive each class's package name (from full_name).
    let class_package: HashMap<&str, String> = classes
        .iter()
        .map(|c| (c.name.as_str(), package_name(&c.full_name, &c.name)))
        .collect();

    // Group classes by package while preserving topo order.
    // BTreeMap gives deterministic alphabetical output.
    let mut by_package: BTreeMap<String, Vec<&ClassDump>> = BTreeMap::new();
    for class in &ordered {
        let pkg = class_package.get(class.name.as_str()).cloned().unwrap_or_else(|| "_unknown".into());
        by_package.entry(pkg).or_default().push(*class);
    }

    // Per-package: emit module with cross-package imports + structs.
    writeln!(out, "// ── Structs, grouped by package ─────────────────────────────────").unwrap();
    writeln!(out).unwrap();

    for (pkg_name, pkg_classes) in &by_package {
        emit_single_package(out, pkg_name, pkg_classes, &class_package, &class_by_name, &known_structs);
    }

    // Flat re-exports at crate root: `use sdk::*` stays ergonomic.
    // Use explicit (non-glob) re-exports, first-occurrence wins, so collisions
    // between packages don't trigger `ambiguous_glob_reexports` errors.
    emit_flat_reexports(out, &by_package);
}

fn emit_single_package(
    out: &mut String,
    pkg_name: &str,
    pkg_classes: &[&ClassDump],
    class_package: &HashMap<&str, String>,
    class_by_name: &HashMap<&str, &ClassDump>,
    known_structs: &HashSet<&str>,
) {
    writeln!(out, "pub mod {pkg_name} {{").unwrap();
    writeln!(out, "    use super::{{FName, FString, TArray}};").unwrap();

    // Collect cross-package dependencies.
    let mut deps: BTreeMap<String, HashSet<String>> = BTreeMap::new();
    for class in pkg_classes {
        collect_class_deps(class, pkg_name, class_package, known_structs, &mut deps);
    }
    for (other_pkg, types) in &deps {
        if other_pkg == pkg_name {
            continue;
        }
        let mut list: Vec<&String> = types.iter().collect();
        list.sort();
        let names: Vec<String> = list.iter().map(|s| sanitize_ident(s)).collect();
        writeln!(out, "    use super::{other_pkg}::{{{}}};", names.join(", ")).unwrap();
    }
    writeln!(out).unwrap();

    for class in pkg_classes {
        emit_struct(out, class, class_by_name, known_structs);
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_flat_reexports(out: &mut String, by_package: &BTreeMap<String, Vec<&ClassDump>>) {
    writeln!(out, "// ── Flat re-exports (first-occurrence wins) ─────────────────────").unwrap();
    let mut seen: HashSet<String> = HashSet::new();
    for (pkg_name, pkg_classes) in by_package {
        let mut items: Vec<String> = Vec::new();
        for class in pkg_classes {
            let ident = sanitize_ident(&class.name);
            if seen.insert(ident.clone()) {
                items.push(ident);
            }
        }
        if !items.is_empty() {
            items.sort();
            writeln!(out, "pub use self::{pkg_name}::{{{}}};", items.join(", ")).unwrap();
        }
    }
    writeln!(out).unwrap();
}

// ═══════════════════════════════════════════════════════════════════
//  Per-struct emission
// ═══════════════════════════════════════════════════════════════════

fn emit_struct(
    out: &mut String,
    class: &ClassDump,
    class_by_name: &HashMap<&str, &ClassDump>,
    known_structs: &HashSet<&str>,
) {
    let struct_name = sanitize_ident(&class.name);
    let parent_name = class.parent.as_deref();
    let parent_size = parent_name
        .and_then(|p| class_by_name.get(p))
        .map(|p| p.size)
        .unwrap_or(0);

    let fields = layout_fields(class, known_structs, parent_size);

    let parent_comment = parent_name
        .map(|p| format!(" (parent: {p}, size: {:#X})", class.size))
        .unwrap_or_else(|| format!(" (size: {:#X})", class.size));

    writeln!(out, "    /// {}{parent_comment}", class.name).unwrap();
    writeln!(out, "    /// Full: {}", class.full_name).unwrap();
    writeln!(out, "    #[repr(C)]").unwrap();
    writeln!(out, "    #[derive(Copy, Clone, Debug)]").unwrap();
    writeln!(out, "    pub struct {struct_name} {{").unwrap();

    let mut cursor: u32 = 0;
    let mut pad_idx: usize = 0;

    // Embed parent struct at offset 0.
    if let Some(pname) = parent_name {
        if class_by_name.contains_key(pname) && parent_size > 0 {
            let parent_ident = sanitize_ident(pname);
            let mut parent_field = to_snake_case(pname);
            if fields.iter().any(|f| f.rust_name == parent_field) {
                parent_field.push_str("_base");
            }
            writeln!(out, "        pub {parent_field}: {parent_ident},").unwrap();
            cursor = parent_size;
        }
    }

    if fields.is_empty() {
        if cursor < class.size {
            let gap = class.size - cursor;
            writeln!(out, "        _pad_{pad_idx}: [u8; {gap:#X}],").unwrap();
        }
    } else {
        for field in &fields {
            if field.offset > cursor {
                let gap = field.offset - cursor;
                writeln!(out, "        _pad_{pad_idx}: [u8; {gap:#X}],").unwrap();
                pad_idx += 1;
            }
            emit_field(out, field);
            cursor = field.offset + field.total_bytes();
        }
        if class.size > cursor {
            let gap = class.size - cursor;
            writeln!(out, "        _pad_{pad_idx}: [u8; {gap:#X}],").unwrap();
        }
    }

    writeln!(out, "    }}").unwrap();

    // Associated constants & bitfield accessors live in impl blocks.
    emit_struct_impl(out, class, &struct_name, &fields);

    // Compile-time size assertion. Rust `#[repr(C)]` pads tail to the
    // struct's alignment; if UE's PropertiesSize isn't a multiple of that
    // alignment, size_of will round up. Compare against both the reported
    // size and its alignment-rounded form so we don't false-positive on
    // alignment-padded layouts.
    if class.size > 0 {
        let size = class.size as usize;
        writeln!(
            out,
            "    const _: () = {{\n        \
             let s = core::mem::size_of::<{struct_name}>();\n        \
             let a = core::mem::align_of::<{struct_name}>();\n        \
             let rounded = ({size:#X} + a - 1) & !(a - 1);\n        \
             assert!(s == {size:#X} || s == rounded);\n    \
             }};"
        )
        .unwrap();
    }
    writeln!(out).unwrap();
}

fn emit_field(out: &mut String, field: &LayoutField) {
    match &field.kind {
        FieldKind::Plain => {
            if field.array_dim > 1 {
                writeln!(
                    out,
                    "        pub {}: [{}; {}], // {:#X}",
                    field.rust_name, field.rust_type, field.array_dim, field.offset
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "        pub {}: {}, // {:#X}",
                    field.rust_name, field.rust_type, field.offset
                )
                .unwrap();
            }
        }
        FieldKind::Bitfield(_) => {
            // Packed byte of one or more UE bitfield bools.
            writeln!(
                out,
                "        pub {}: u8, // {:#X} (bitfield)",
                field.rust_name, field.offset
            )
            .unwrap();
        }
    }
}

fn emit_struct_impl(
    out: &mut String,
    class: &ClassDump,
    struct_name: &str,
    fields: &[LayoutField],
) {
    let has_any_consts = class.size > 0
        || !fields.is_empty()
        || !class.functions.is_empty();
    if !has_any_consts {
        return;
    }

    writeln!(out, "    impl {struct_name} {{").unwrap();

    if class.size > 0 {
        writeln!(out, "        pub const SIZE: usize = {:#X};", class.size).unwrap();
    }

    for field in fields {
        match &field.kind {
            FieldKind::Plain => {
                writeln!(
                    out,
                    "        pub const OFFSET_{}: usize = {:#X};",
                    field.const_name, field.offset
                )
                .unwrap();
            }
            FieldKind::Bitfield(_) => {
                writeln!(
                    out,
                    "        pub const OFFSET_{}: usize = {:#X};",
                    field.const_name, field.offset
                )
                .unwrap();
            }
        }
    }

    // UFunction native function-pointer addresses (image-base-relative would
    // require base-tracking here; we emit raw absolute addresses as read).
    for func in &class.functions {
        if func.native_func == 0 {
            continue;
        }
        let ident = sanitize_ident(&func.name);
        writeln!(
            out,
            "        pub const FN_{ident}: u64 = {:#X};",
            func.native_func
        )
        .unwrap();
    }

    // Bitfield accessor methods.
    for field in fields {
        if let FieldKind::Bitfield(bits) = &field.kind {
            for bit in bits {
                let method = sanitize_ident(&to_snake_case(&bit.name));
                writeln!(
                    out,
                    "        #[inline] pub fn {method}(&self) -> bool {{ (self.{} & {:#X}) != 0 }}",
                    field.rust_name, bit.mask
                )
                .unwrap();
            }
        }
    }

    // UFunction signatures as commented stubs (kept for discoverability).
    if !class.functions.is_empty() {
        writeln!(out, "        // ── UFunction signatures (call via ProcessEvent) ──").unwrap();
        for func in &class.functions {
            emit_function_stub(out, func);
        }
    }

    writeln!(out, "    }}").unwrap();
}

fn emit_function_stub(out: &mut String, func: &FunctionDump) {
    const FUNC_NET: u32 = 0x00000040;
    const FUNC_NET_SERVER: u32 = 0x00200000;
    const FUNC_NET_CLIENT: u32 = 0x01000000;
    const FUNC_BLUEPRINT_CALLABLE: u32 = 0x04000000;

    let mut tags = Vec::new();
    if (func.flags & FUNC_NET) != 0 { tags.push("Net"); }
    if (func.flags & FUNC_NET_SERVER) != 0 { tags.push("Server"); }
    if (func.flags & FUNC_NET_CLIENT) != 0 { tags.push("Client"); }
    if (func.flags & FUNC_BLUEPRINT_CALLABLE) != 0 { tags.push("BlueprintCallable"); }

    let params_str: Vec<String> = func.params.iter().map(|p| {
        let ty = map_param_type(&p.prop_type);
        format!("{}: {ty}", to_snake_case(&p.name))
    }).collect();

    let tag_str = if tags.is_empty() {
        String::new()
    } else {
        format!(" // [{}]", tags.join(", "))
    };

    writeln!(
        out,
        "        //   fn {}({}){tag_str}",
        to_snake_case(&func.name),
        params_str.join(", "),
    )
    .unwrap();
}

// ═══════════════════════════════════════════════════════════════════
//  Layout synthesis
// ═══════════════════════════════════════════════════════════════════

struct LayoutField {
    rust_name: String,
    rust_type: String,
    const_name: String,
    offset: u32,
    size: u32,
    array_dim: u32,
    kind: FieldKind,
}

enum FieldKind {
    Plain,
    Bitfield(Vec<BitfieldBit>),
}

struct BitfieldBit {
    name: String,
    mask: u8,
}

impl LayoutField {
    fn total_bytes(&self) -> u32 {
        self.size * self.array_dim.max(1)
    }
}

/// Build a sorted, non-overlapping list of fields for a class.
/// Bitfield bools at the same offset are grouped into a single `u8` field.
fn layout_fields(
    class: &ClassDump,
    known_structs: &HashSet<&str>,
    min_offset: u32,
) -> Vec<LayoutField> {
    // Bucket bools by offset so we can group native bitfields.
    let mut bool_groups: BTreeMap<u32, Vec<&PropertyDump>> = BTreeMap::new();
    let mut non_bool: Vec<&PropertyDump> = Vec::new();

    for prop in &class.properties {
        if prop.name.is_empty() || prop.size == 0 {
            continue;
        }
        if prop.offset < min_offset {
            continue;
        }
        if prop.prop_type == "BoolProperty" && prop.size == 1 {
            bool_groups.entry(prop.offset).or_default().push(prop);
        } else {
            non_bool.push(prop);
        }
    }

    let mut out: Vec<LayoutField> = Vec::new();

    // Emit grouped bool bytes.
    for (offset, group) in bool_groups {
        let any_bitfield = group.iter().any(|p| {
            p.bit_index.is_some()
                || p.field_mask.map(|m| m != 0xFF).unwrap_or(false)
        });

        if any_bitfield {
            // Pack all bools in this group into a single synthetic u8 byte.
            let mut bits: Vec<BitfieldBit> = Vec::new();
            let mut seen_masks: HashSet<u8> = HashSet::new();
            for prop in &group {
                let mask = prop.field_mask.unwrap_or(0xFF);
                if !seen_masks.insert(mask) {
                    continue;
                }
                bits.push(BitfieldBit {
                    name: prop.name.clone(),
                    mask,
                });
            }
            let synth_name = format!("_bitfield_{offset:X}");
            out.push(LayoutField {
                rust_name: synth_name.clone(),
                rust_type: "u8".into(),
                const_name: format!("Bitfield_{offset:X}"),
                offset,
                size: 1,
                array_dim: 1,
                kind: FieldKind::Bitfield(bits),
            });
        } else {
            // All full-byte bools at this offset — keep just the first (UE often
            // emits duplicates for replication sub-properties).
            let prop = group[0];
            out.push(LayoutField {
                rust_name: to_snake_case(&prop.name),
                rust_type: "bool".into(),
                const_name: sanitize_ident(&prop.name),
                offset: prop.offset,
                size: 1,
                array_dim: prop.array_dim.max(1),
                kind: FieldKind::Plain,
            });
        }
    }

    // Emit non-bool fields.
    for prop in non_bool {
        let rust_name = to_snake_case(&prop.name);
        let rust_type = map_type(prop, known_structs);
        out.push(LayoutField {
            rust_name,
            rust_type,
            const_name: sanitize_ident(&prop.name),
            offset: prop.offset,
            size: prop.size,
            array_dim: prop.array_dim.max(1),
            kind: FieldKind::Plain,
        });
    }

    out.sort_by_key(|f| f.offset);

    // Drop overlapping fields (keeps the first at any given range).
    let mut result: Vec<LayoutField> = Vec::new();
    let mut end: u32 = 0;
    for field in out {
        if field.offset < end {
            continue;
        }
        end = field.offset + field.total_bytes();
        result.push(field);
    }
    result
}

// ═══════════════════════════════════════════════════════════════════
//  Dependency collection (for cross-module `use` statements)
// ═══════════════════════════════════════════════════════════════════

fn collect_class_deps(
    class: &ClassDump,
    own_pkg: &str,
    class_package: &HashMap<&str, String>,
    known_structs: &HashSet<&str>,
    out: &mut BTreeMap<String, HashSet<String>>,
) {
    let mut record = |ty: &str| {
        if !known_structs.contains(ty) {
            return;
        }
        if let Some(other_pkg) = class_package.get(ty) {
            if other_pkg != own_pkg {
                out.entry(other_pkg.clone())
                    .or_default()
                    .insert(ty.to_string());
            }
        }
    };

    if let Some(parent) = &class.parent {
        record(parent);
    }
    for prop in &class.properties {
        match prop.prop_type.as_str() {
            "ObjectProperty" | "ObjectPtrProperty" | "StructProperty" => {
                if let Some(inner) = &prop.inner_type {
                    record(inner);
                }
            }
            "ArrayProperty" => {
                // ArrayProperty's inner_type is the element's *property type* name,
                // not a class name (e.g. "ObjectProperty") — nothing to import.
            }
            _ => {}
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Package name derivation
// ═══════════════════════════════════════════════════════════════════

/// Derive the Rust module name for a UClass from its full_name.
///
/// "/Script/Engine.Actor"              -> "engine"
/// "CoreUObject.Class.Object"          -> "coreuobject"
/// "/Game/Blueprints/BP_Foo.BP_Foo_C"  -> "bp_foo"
/// ""                                  -> "_unknown"
fn package_name(full_name: &str, _fallback: &str) -> String {
    let before_dot = full_name.split('.').next().unwrap_or(full_name);
    let stripped = before_dot.strip_prefix("/Script/").unwrap_or(before_dot);
    let last = stripped.rsplit('/').next().unwrap_or(stripped);
    let mut s: String = last
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() {
        return "_unknown".into();
    }
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    // Avoid colliding with Rust keywords at the module level.
    if is_rust_keyword(&s) {
        s.push('_');
    }
    s
}

// ═══════════════════════════════════════════════════════════════════
//  Type mapping
// ═══════════════════════════════════════════════════════════════════

fn map_type(prop: &PropertyDump, known_structs: &HashSet<&str>) -> String {
    match prop.prop_type.as_str() {
        "BoolProperty" => "bool".into(),
        "Int8Property" | "ByteProperty" => {
            if prop.size == 1 { "u8".into() } else { format!("[u8; {:#X}]", prop.size) }
        }
        "Int16Property" => "i16".into(),
        "UInt16Property" => "u16".into(),
        "IntProperty" => "i32".into(),
        "UInt32Property" => "u32".into(),
        "Int64Property" => "i64".into(),
        "UInt64Property" => "u64".into(),
        "FloatProperty" => "f32".into(),
        "DoubleProperty" => "f64".into(),

        "NameProperty" => "FName".into(),
        "StrProperty" => "FString".into(),
        "TextProperty" => format!("[u8; {:#X}]", prop.size),

        "ObjectProperty" | "ObjectPtrProperty" => {
            if let Some(inner) = &prop.inner_type {
                let name = sanitize_ident(inner);
                if known_structs.contains(inner.as_str()) {
                    format!("*const {name}")
                } else {
                    format!("*const u8 /* {name} */")
                }
            } else {
                "*const u8".into()
            }
        }
        "WeakObjectProperty" | "LazyObjectProperty" | "SoftObjectProperty"
        | "ClassProperty" | "SoftClassProperty" => {
            format!("[u8; {:#X}]", prop.size)
        }

        "ArrayProperty" => {
            if let Some(inner) = &prop.inner_type {
                let elem = match inner.as_str() {
                    "ObjectProperty" | "ObjectPtrProperty" => "*const u8",
                    "IntProperty" => "i32",
                    "FloatProperty" => "f32",
                    "ByteProperty" | "Int8Property" => "u8",
                    "UInt32Property" => "u32",
                    "Int64Property" => "i64",
                    "UInt64Property" => "u64",
                    "BoolProperty" => "bool",
                    "NameProperty" => "FName",
                    "StrProperty" => "FString",
                    _ => "u8",
                };
                format!("TArray<{elem}>")
            } else {
                "TArray<u8>".into()
            }
        }
        "MapProperty" | "SetProperty" => format!("[u8; {:#X}]", prop.size),

        "StructProperty" => {
            if let Some(inner) = &prop.inner_type {
                let name = sanitize_ident(inner);
                if known_structs.contains(inner.as_str()) {
                    name
                } else {
                    format!("[u8; {:#X}] /* {name} */", prop.size)
                }
            } else {
                format!("[u8; {:#X}]", prop.size)
            }
        }

        "EnumProperty" => {
            // Emit as primitive; the variant names live in `pub mod enums`.
            let ty = match prop.size {
                1 => "u8",
                2 => "u16",
                4 => "u32",
                8 => "u64",
                _ => "",
            };
            if ty.is_empty() {
                format!("[u8; {:#X}]", prop.size)
            } else if let Some(inner) = &prop.inner_type {
                format!("{ty} /* enum {inner} */")
            } else {
                ty.into()
            }
        }

        _ => format!("[u8; {:#X}]", prop.size),
    }
}

fn map_param_type(prop_type: &str) -> &'static str {
    match prop_type {
        "BoolProperty" => "bool",
        "Int8Property" | "ByteProperty" => "u8",
        "Int16Property" => "i16",
        "UInt16Property" => "u16",
        "IntProperty" => "i32",
        "UInt32Property" => "u32",
        "Int64Property" => "i64",
        "UInt64Property" => "u64",
        "FloatProperty" => "f32",
        "DoubleProperty" => "f64",
        "NameProperty" => "FName",
        "StrProperty" => "FString",
        "ObjectProperty" | "ObjectPtrProperty" => "*const u8",
        _ => "*const u8",
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Topological sort
// ═══════════════════════════════════════════════════════════════════

fn topo_sort<'a>(
    classes: &'a [ClassDump],
    by_name: &HashMap<&str, &'a ClassDump>,
) -> Vec<&'a ClassDump> {
    let mut visited: HashSet<&str> = HashSet::new();
    let mut result: Vec<&ClassDump> = Vec::with_capacity(classes.len());

    for class in classes {
        topo_visit(class, by_name, &mut visited, &mut result);
    }
    result
}

fn topo_visit<'a>(
    class: &'a ClassDump,
    by_name: &HashMap<&str, &'a ClassDump>,
    visited: &mut HashSet<&'a str>,
    result: &mut Vec<&'a ClassDump>,
) {
    if visited.contains(class.name.as_str()) {
        return;
    }
    visited.insert(&class.name);

    if let Some(parent) = &class.parent {
        if let Some(pcls) = by_name.get(parent.as_str()) {
            topo_visit(pcls, by_name, visited, result);
        }
    }
    result.push(class);
}

// ═══════════════════════════════════════════════════════════════════
//  Helpers: identifier sanitization, name lookup, timestamp
// ═══════════════════════════════════════════════════════════════════

fn find_property_offset(
    classes: &[ClassDump],
    class_name: &str,
    prop_name: &str,
) -> Option<usize> {
    let class = classes.iter().find(|c| c.name == class_name)?;
    let prop = class.properties.iter().find(|p| p.name == prop_name)?;
    Some(prop.offset as usize)
}

fn to_snake_case(name: &str) -> String {
    let mut result = String::with_capacity(name.len() + 4);
    let chars: Vec<char> = name.chars().collect();

    for (i, &c) in chars.iter().enumerate() {
        if c == '_' {
            result.push('_');
            continue;
        }
        if c.is_uppercase() {
            if i > 0 {
                let prev = chars[i - 1];
                let next_is_lower = chars.get(i + 1).map_or(false, |n| n.is_lowercase());
                if prev.is_lowercase()
                    || prev.is_ascii_digit()
                    || (prev.is_uppercase() && next_is_lower)
                {
                    result.push('_');
                }
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }

    sanitize_ident(&result)
}

fn sanitize_ident(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if s.is_empty() {
        return "_empty".into();
    }
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if is_rust_keyword(&s) {
        s.push('_');
    }
    s
}

fn is_rust_keyword(s: &str) -> bool {
    // Includes strict keywords, reserved keywords, and `Self` (capital S) —
    // UE names are case-preserving and "Self" shows up as an enum variant.
    matches!(
        s,
        "Self" | "type" | "self" | "super" | "crate" | "mod" | "fn" | "struct" | "enum"
            | "trait" | "impl" | "use" | "pub" | "const" | "static" | "let" | "mut" | "ref"
            | "as" | "in" | "for" | "if" | "else" | "while" | "loop" | "match" | "return"
            | "break" | "continue" | "move" | "box" | "where" | "async" | "await" | "dyn"
            | "true" | "false" | "extern" | "unsafe" | "yield" | "do" | "macro" | "priv"
            | "abstract" | "become" | "final" | "override" | "typeof" | "unsized" | "virtual"
    )
}

fn timestamp() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!("unix:{now}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ue::props::{ClassDump, EnumDump, EnumVariant, FunctionDump, PropertyDump};

    #[test]
    fn test_snake_case() {
        assert_eq!(to_snake_case("OwningGameInstance"), "owning_game_instance");
        assert_eq!(to_snake_case("LocalPlayers"), "local_players");
        assert_eq!(to_snake_case("AcknowledgedPawn"), "acknowledged_pawn");
        assert_eq!(to_snake_case("bHidden"), "b_hidden");
        assert_eq!(to_snake_case("HP"), "hp");
        assert_eq!(to_snake_case("MaxHP"), "max_hp");
        assert_eq!(to_snake_case("already_snake"), "already_snake");
    }

    #[test]
    fn test_sanitize_keywords() {
        assert_eq!(sanitize_ident("type"), "type_");
        assert_eq!(sanitize_ident("self"), "self_");
        assert_eq!(sanitize_ident("World"), "World");
        assert_eq!(sanitize_ident("123abc"), "_123abc");
    }

    #[test]
    fn test_package_name() {
        assert_eq!(package_name("/Script/Engine.Actor", "Actor"), "engine");
        assert_eq!(package_name("CoreUObject.Class.Object", "Object"), "coreuobject");
        assert_eq!(package_name("/Game/Blueprints/BP_Foo.BP_Foo_C", "BP_Foo_C"), "bp_foo");
        assert_eq!(package_name("", ""), "_unknown");
        assert_eq!(package_name("Engine.Actor", "Actor"), "engine");
    }

    fn mk_prop(name: &str, ty: &str, off: u32, size: u32) -> PropertyDump {
        PropertyDump {
            name: name.into(),
            prop_type: ty.into(),
            offset: off,
            size,
            array_dim: 1,
            inner_type: None,
            bit_index: None,
            field_mask: None,
        }
    }

    fn mk_bitfield_bool(name: &str, off: u32, bit: u8) -> PropertyDump {
        PropertyDump {
            name: name.into(),
            prop_type: "BoolProperty".into(),
            offset: off,
            size: 1,
            array_dim: 1,
            inner_type: None,
            bit_index: Some(bit),
            field_mask: Some(1u8 << bit),
        }
    }

    #[test]
    fn test_generate_rust_structure() {
        let object = ClassDump {
            name: "Object".into(),
            full_name: "/Script/CoreUObject.Object".into(),
            parent: None,
            size: 0x30,
            properties: vec![],
            functions: vec![],
        };
        let actor = ClassDump {
            name: "Actor".into(),
            full_name: "/Script/Engine.Actor".into(),
            parent: Some("Object".into()),
            size: 0x80,
            properties: vec![
                PropertyDump {
                    name: "Owner".into(),
                    prop_type: "ObjectProperty".into(),
                    offset: 0x30,
                    size: 8,
                    array_dim: 1,
                    inner_type: Some("Actor".into()),
                    bit_index: None,
                    field_mask: None,
                },
                mk_bitfield_bool("bHidden", 0x60, 0),
                mk_bitfield_bool("bReplicates", 0x60, 1),
                mk_prop("CreationTime", "FloatProperty", 0x70, 4),
            ],
            functions: vec![FunctionDump {
                name: "K2_DestroyActor".into(),
                full_name: "/Script/Engine.Actor.K2_DestroyActor".into(),
                flags: 0x00000040, // FUNC_Net
                native_func: 0x0000_1234_5678_9ABC,
                params: vec![],
            }],
        };
        let classes = vec![object, actor];

        let my_enum = EnumDump {
            name: "EMyFlag".into(),
            full_name: "/Script/Engine.EMyFlag".into(),
            variants: vec![
                EnumVariant { name: "EMyFlag::None".into(), value: 0 },
                EnumVariant { name: "EMyFlag::Foo".into(), value: 1 },
            ],
        };

        let src = generate_rust(&classes, &[my_enum], None, 0);

        // Common types + derives.
        assert!(src.contains("pub struct FName"), "FName missing");
        assert!(src.contains("#[derive(Copy, Clone, Debug)]"), "derives missing");

        // Enum module.
        assert!(src.contains("pub mod enums"), "enums module missing");
        assert!(src.contains("pub mod EMyFlag"), "EMyFlag module missing");
        assert!(src.contains("pub const Foo: i64 = 1"), "enum const missing");

        // Package modules.
        assert!(src.contains("pub mod coreuobject"), "coreuobject pkg missing");
        assert!(src.contains("pub mod engine"), "engine pkg missing");

        // Cross-module import (engine.Actor references coreuobject.Object).
        assert!(src.contains("use super::coreuobject::{Object}"), "cross-pkg use missing");

        // Struct + parent embed.
        assert!(src.contains("pub struct Actor"), "Actor struct missing");
        assert!(src.contains("pub object: Object,"), "parent embed missing");

        // OFFSET_ consts and SIZE.
        assert!(src.contains("pub const SIZE: usize = 0x80"), "SIZE const missing");
        assert!(src.contains("pub const OFFSET_Owner: usize = 0x30"), "OFFSET_Owner missing");
        assert!(src.contains("pub const OFFSET_CreationTime: usize = 0x70"), "OFFSET_CreationTime missing");

        // UFunction const.
        assert!(
            src.contains("pub const FN_K2_DestroyActor: u64 = 0x123456789ABC"),
            "FN_ const missing or wrong"
        );

        // Bitfield accessor methods.
        assert!(src.contains("_bitfield_60: u8"), "packed bitfield byte missing");
        assert!(src.contains("fn b_hidden(&self) -> bool"), "bHidden accessor missing");
        assert!(src.contains("fn b_replicates(&self) -> bool"), "bReplicates accessor missing");

        // Size assertion.
        assert!(
            src.contains("let s = core::mem::size_of::<Actor>()")
                && src.contains("assert!(s == 0x80 || s == rounded)"),
            "size assert missing"
        );

        // Flat re-exports.
        assert!(src.contains("pub use self::coreuobject::{Object}"), "flat re-export missing");
        assert!(src.contains("pub use self::engine::{Actor}"), "flat re-export missing");
    }

    /// Actually compile the generated source with rustc to catch syntax/type errors
    /// that substring checks miss (mismatched braces, bad identifiers, etc.).
    #[test]
    fn test_generated_code_compiles() {
        use std::io::Write;
        use std::process::Command;

        // Build a small but representative dump: 3 classes across 2 packages,
        // parent embedding, object pointer, bitfield, normal bool, all-prim types,
        // TArray, one enum, one UFunction.
        let object = ClassDump {
            name: "Object".into(),
            full_name: "/Script/CoreUObject.Object".into(),
            parent: None,
            size: 0x30,
            properties: vec![],
            functions: vec![],
        };
        let other = ClassDump {
            name: "OtherStruct".into(),
            full_name: "/Script/CoreUObject.OtherStruct".into(),
            parent: None,
            size: 0x18,
            properties: vec![
                mk_prop("A", "IntProperty", 0x0, 4),
                mk_prop("B", "FloatProperty", 0x4, 4),
            ],
            functions: vec![],
        };
        let actor = ClassDump {
            name: "Actor".into(),
            full_name: "/Script/Engine.Actor".into(),
            parent: Some("Object".into()),
            size: 0x100,
            properties: vec![
                PropertyDump {
                    name: "Owner".into(),
                    prop_type: "ObjectProperty".into(),
                    offset: 0x30,
                    size: 8,
                    array_dim: 1,
                    inner_type: Some("Actor".into()),
                    bit_index: None,
                    field_mask: None,
                },
                PropertyDump {
                    name: "Tags".into(),
                    prop_type: "ArrayProperty".into(),
                    offset: 0x40,
                    size: 16,
                    array_dim: 1,
                    inner_type: Some("NameProperty".into()),
                    bit_index: None,
                    field_mask: None,
                },
                mk_bitfield_bool("bHidden", 0x60, 0),
                mk_bitfield_bool("bReplicates", 0x60, 1),
                PropertyDump {
                    name: "bCanBeDamaged".into(),
                    prop_type: "BoolProperty".into(),
                    offset: 0x61,
                    size: 1,
                    array_dim: 1,
                    inner_type: None,
                    bit_index: None,
                    field_mask: Some(0xFF),
                },
                mk_prop("CreationTime", "FloatProperty", 0x64, 4),
                PropertyDump {
                    name: "NestedStruct".into(),
                    prop_type: "StructProperty".into(),
                    offset: 0x68,
                    size: 0x18,
                    array_dim: 1,
                    inner_type: Some("OtherStruct".into()),
                    bit_index: None,
                    field_mask: None,
                },
                mk_prop("UnknownBlob", "StructProperty", 0x80, 0x10),
            ],
            functions: vec![
                FunctionDump {
                    name: "K2_DestroyActor".into(),
                    full_name: "/Script/Engine.Actor.K2_DestroyActor".into(),
                    flags: 0x00000040,
                    native_func: 0x0000_1234_5678_9ABC,
                    params: vec![mk_prop("Reason", "IntProperty", 0x0, 4)],
                },
                FunctionDump {
                    name: "self".into(), // keyword — must be escaped
                    full_name: "/Script/Engine.Actor.self".into(),
                    flags: 0,
                    native_func: 0x1000,
                    params: vec![],
                },
            ],
        };
        let classes = vec![object, other, actor];

        let my_enum = EnumDump {
            name: "EMyFlag".into(),
            full_name: "/Script/Engine.EMyFlag".into(),
            variants: vec![
                EnumVariant { name: "EMyFlag::None".into(), value: 0 },
                EnumVariant { name: "EMyFlag::Foo".into(), value: 1 },
                EnumVariant { name: "EMyFlag::type".into(), value: 2 }, // keyword
            ],
        };

        let src = generate_rust(&classes, &[my_enum], None, 0);

        // Optionally dump the sample to a path for manual inspection.
        if let Ok(path) = std::env::var("UE5_DUMPER_SAMPLE_OUT") {
            std::fs::write(&path, &src).expect("write sample");
            eprintln!("sample SDK written to {path}");
        }

        // Write to a temp file and invoke rustc --emit=metadata to check it parses+types.
        let tmp = std::env::temp_dir().join(format!("ue5_dumper_probe_{}.rs", std::process::id()));
        let mut f = std::fs::File::create(&tmp).expect("create tmp");
        f.write_all(src.as_bytes()).expect("write tmp");
        drop(f);

        let meta_out = tmp.with_extension("rmeta");
        let output = Command::new("rustc")
            .arg("--edition=2021")
            .arg("--crate-type=lib")
            .arg("--emit=metadata")
            .arg("-o")
            .arg(&meta_out)
            .arg(&tmp)
            .output();

        // Clean up tmp source regardless of outcome
        let _ = std::fs::remove_file(&meta_out);
        let src_path = tmp.clone();

        match output {
            Ok(out) if out.status.success() => {
                let _ = std::fs::remove_file(src_path);
            }
            Ok(out) => {
                let stderr = String::from_utf8_lossy(&out.stderr);
                panic!(
                    "generated code failed to compile:\n{stderr}\n\nsource kept at: {}",
                    src_path.display()
                );
            }
            Err(e) => {
                // rustc not available in environment — skip softly.
                eprintln!("skipping compile check: could not run rustc: {e}");
                let _ = std::fs::remove_file(src_path);
            }
        }
    }
}
